apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: lauravrv/frontend-app:v1
        ports:
        - containerPort: 80
        env:
        - name: AUTH_API_ADDRESS
          value: "http://auth-service.auth.svc.cluster.local:8000"
        - name: TODOS_API_ADDRESS
          value: "http://todos-service.todos.svc.cluster.local:8082"
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  namespace: frontend
spec:
  selector:
    app: frontend
  ports:
  - port: 80
    targetPort: 80
