apiVersion: apps/v1
kind: Deployment
metadata:
  name: users
  namespace: auth
spec:
  replicas: 1
  selector:
    matchLabels:
      app: users
  template:
    metadata:
      labels:
        app: users
    spec:
      containers:
      - name: users
        image: lauravrv/users-app:v1
        ports:
        - containerPort: 8083
        resources:
          requests:
            cpu: "100m"
            memory: "256Mi"
          limits:
            cpu: "300m"
            memory: "512Mi"
        env:
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: JWT_SECRET
        - name: SERVER_PORT
          value: "8083"
