apiVersion: v1
kind: ConfigMap
metadata:
  name: frontend-config
  namespace: frontend
data:
  AUTH_API_ADDRESS: "http://auth-service.auth.svc.cluster.local:8000"
  TODOS_API_ADDRESS: "http://todos-service.todos.svc.cluster.local:8082"
