apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
  namespace: auth
type: Opaque
stringData:
  JWT_SECRET: "PRFT"
---
apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
  namespace: todos
type: Opaque
stringData:
  JWT_SECRET: "PRFT"
