apiVersion: v1
kind: ConfigMap
metadata:
  name: todos-config
  namespace: todos
data:
  TODO_API_PORT: "8082"
  REDIS_HOST: "redis-service.data.svc.cluster.local"
  REDIS_PORT: "6379"
  REDIS_CHANNEL: "log_channel"
  ZIPKIN_URL: "http://zipkin-service.data.svc.cluster.local:9411"
